install.packages('shiny')
install.packages('shinyEventLogger')

install.packages('dplyr')
install.packages('DiagrammeR')

install.packages('bupaR')
install.packages('processmapR')


install.packages('bupaR')
install.packages('daqapo')
install.packages('datetime')
install.packages('dplyr')
install.packages('edeaR')
install.packages('eventdataR')
install.packages('heuristicsmineR')
install.packages('jsonlite')
install.packages('lubridate')
install.packages('petrinetR')
install.packages('pm4py')
install.packages('processanimateR')
install.packages('processcheckR')
install.packages('processmapR')
install.packages('processmonitR')
install.packages('shiny')
install.packages('shinycssloaders')
install.packages('tidyr')
install.packages('tidyverse')
install.packages('xesreadR')
install.packageslibrary('ggplot2')

install.packages('DiagrammeR')
